### ISSUE TITLE
ftp.events undefined

### ISSUE THREAD

**Issue by yieme** [sparkida/ftpimp#13]
README.md example code:

```js
var FTP = require('ftpimp'),
    ftp = FTP.create(config),
    connected = function () {
        console.log('connected to remote FTP server');
    };

ftp.events.once('ready', connected);
```

Gives **can not call method 'once' on undefined** error.

Changing `ftp.events.once('ready', connected);` to `ftp.once('ready', connected);` seems to do the trick.

**Comment by sparkida** [comment]
thank you for this! I'll get an update in this weekend

**Comment by Tsopic** [comment]
Does not seem to be resolved yet :/

**Comment by sparkida** [comment]
@yieme would you want to create a PR and submit your fix? Otherwise, thanks for the fix, I'll check back later and merge it. Sorry @Tsopic for delay, consumed by work.
