### ISSUE TITLE
Invalid buffer concatenation

### ISSUE THREAD

**Issue by niko-dotlabs** [sparkida/ftpimp#14]
In line 436 of index.js it looks like buffers should be concatenated. the way it's done the buffers get implicitly converted to strings.

Update: Just saw the whole pipeData is handled as string. maybe this should be a buffer leaving encodings to users.

**Comment by sparkida** [comment]
good call, thanks for the issue. I'll look into this over the weekend

**Comment by niko-dotlabs** [comment]
you're welcome and thanks for your work! another thing i just 
encountered is that in index.js in line 764 you access the socket 
property *socket.remoteAddress*. It seems that the case where a socket 
is destroyed and the value gets undefined (according to node docs) isn't 
always handled correctly. I just got an issue with the following message:

TypeError: Cannot read property 'split' of undefined
     at Socket.handle.connected (c:\Users\ffrau\WT-NMP\WWW\offerfetcher-agent\node_modules\dot-apicrawler\node_modules\ftpimp\index.js:764:54)
     at Socket.emit (events.js:104:17)
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1001:10)


Am 10.05.2016 um 16:32 schrieb Nick Riley:

**Comment by sparkida** [comment]
@niko-dotlabs, sorry for the delay, I've been swamped at work. These are solid enhancements, ty, feel free to make the solutions yourself and submit a PR, otherwise, I'll merge the fixes in soon.

**Comment by sparkida** [comment]
@niko-dotlabs thanks for providing details. That's a good call with the buffer, I shouldn't have been forcing it to string. Now the data returned in 3.0 will be a Buffer object. I also added in some functionality to retry if the socket is somehow lost, this will happen 3 times before giving up and the server will exit with a predictable error this time. That should give the admin enough to restart the process / connection if desired. Thanks again.

-Nick
