### ISSUE TITLE
ftp.ls returning no error and no result

### ISSUE THREAD

**Issue by iinnaann** [sparkida/ftpimp#30]
I'm trying to list all files in the ftp-server with the following code. But the ls command returns always a empty array and the error is null. If I turn the debug on, I can see that the .ls function have information/files in the pipedata: Is there something broken or something wrong with my code?

`ftp.ls('/USB-0', function(err, filelist) {
        console.log(err);
        console.log(filelist);
        connectionStatus = false;
        setTimeout(function() {
            res.json(filelist.length);
        }, 10);
    });`

**Debug**
`calling : _checkProc > LIST /USB-0 {}
check process for end:  ExeQueue {
  command: 'LIST /USB-0',
  method: 'LIST',
  pipeData:
   [ <Buffer 30 33 2d 31 34 2d 31 37 20 20 30 33 3a 30 32 50 4d 20 20 20 20 20 2
0 20 20 20 20 20 20 20 20 20 20 34 39 31 35 32 20 50 72 75 66 73 74 61 6e 64 5f
30 31 30 30 30 30 2e 53 45 54 0d 0a>,
     <Buffer 30 33 2d 31 34 2d 31 37 20 20 30 33 3a 31 32 50 4d 20 20 20 20 20 2
0 20 20 20 20 20 20 20 20 20 20 20 33 34 32 34 20 50 72 75 66 73 74 61 6e 64 5f
30 31 30 30 30 30 30 2e 43 53 56 0d 0a 30 33 2d 31 34 2d 31 37 20 20 30 33 3a 31
 33 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 34 31 30 33 33 20 50 7
2 75 66 73 74 61 6e 64 5f 30 31 30 30 30 30 31 2e 43 53 56 0d 0a 30 33 2d 31 34
2d 31 37 20 20 30 33 3a 31 33 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
 20 20 33 34 32 34 20 50 72 75 66 73 74 61 6e 64 5f 30 31 30 30 30 30 32 2e 43 5
3 56 0d 0a 30 33 2d 31 34 2d 31 37 20 20 30 33 3a 31 38 50 4d 20 20 20 20 20 20
20 20 20 20 20 20 20 20 20 20 20 33 34 32 35 20 50 72 75 66 73 74 61 6e 64 5f 30
 31 30 30 30 30 33 2e 43 53 56 0d 0a 30 33 2d 31 34 2d 31 37 20 20 30 33 3a 31 3
8 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 33 34 32 35 20 50 72
75 66 73 74 61 6e 64 5f 30 31 30 30 30 30 34 2e 43 53 56 0d 0a 30 33 2d 31 34 2d
 31 37 20 20 30 33 3a 32 30 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 2
0 34 31 30 33 33 20 50 72 75 66 73 74 61 6e 64 5f 30 31 30 30 30 30 35 2e 43 53
56 0d 0a 30 33 2d 31 34 2d 31 37 20 20 30 33 3a 32 30 50 4d 20 20 20 20 20 20 20
 20 20 20 20 20 20 20 20 20 20 33 34 32 35 20 50 72 75 66 73 74 61 6e 64 5f 30 3
1 30 30 30 30 36 2e 43 53 56 0d 0a 30 33 2d 31 34 2d 31 37 20 20 30 33 3a 32 30
50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 34 34 32 33 37 20 50 72 75
 66 73 74 61 6e 64 5f 30 31 30 30 30 30 37 2e 43 53 56 0d 0a 30 33 2d 31 ... >,
     <Buffer 3a 31 39 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 3
5 39 38 33 20 50 72 75 66 73 74 61 6e 64 5f 30 31 30 30 30 30 2e 43 53 56 0d 0a
30 33 2d 31 35 2d 31 37 20 20 30 32 3a 34 31 50 4d 20 20 20 20 20 20 20 20 20 20
 20 20 20 20 20 20 34 39 31 35 32 20 54 65 73 74 4d 65 73 73 75 6e 67 30 30 30 3
0 2e 53 45 54 0d 0a 30 33 2d 31 35 2d 31 37 20 20 30 32 3a 34 32 50 4d 20 20 20
20 20 20 20 20 20 20 20 20 20 20 20 20 20 36 30 30 30 20 54 65 73 74 4d 65 73 73
 75 6e 67 30 30 31 32 2e 57 54 53 0d 0a 30 33 2d 31 35 2d 31 37 20 20 30 32 3a 3
4 32 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 54
65 73 74 4d 65 73 73 75 6e 67 30 30 31 32 2e 48 44 53 0d 0a 30 33 2d 31 35 2d 31
 37 20 20 30 32 3a 34 32 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 3
1 32 37 35 32 20 54 65 73 74 4d 65 73 73 75 6e 67 30 30 31 32 2e 43 53 56 0d 0a
30 33 2d 31 35 2d 31 37 20 20 30 32 3a 34 39 50 4d 20 20 20 20 20 20 20 20 20 20
 20 20 20 20 20 20 34 39 31 35 32 20 54 65 73 74 4d 65 73 73 75 6e 67 30 30 30 3
1 2e 53 45 54 0d 0a 30 33 2d 31 35 2d 31 37 20 20 30 32 3a 35 32 50 4d 20 20 20
20 20 20 20 20 20 20 20 20 20 20 20 31 32 30 30 30 30 20 54 65 73 74 4d 65 73 73
 75 6e 67 30 30 31 33 2e 57 54 53 0d 0a 30 33 2d 31 35 2d 31 37 20 20 30 32 3a 3
5 32 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 54
65 73 74 4d 65 73 73 75 6e 67 30 30 31 33 2e 48 44 53 0d 0a 30 33 2d 31 35 2d 31
 37 20 20 30 32 3a 35 32 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 ... >,
     <Buffer 30 33 2d 31 36 2d 31 37 20 20 30 34 3a 33 31 50 4d 20 20 20 20 20 2
0 20 20 20 20 20 20 20 20 20 20 35 31 30 37 33 20 54 65 73 74 4d 65 73 73 75 6e
67 30 30 32 34 2e 43 53 56 0d 0a 30 33 2d 31 36 2d 31 37 20 20 30 34 3a 33 32 50
 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 35 37 30 36 30 20 54 65 73 7
4 4d 65 73 73 75 6e 67 30 30 32 35 2e 57 54 53 0d 0a 30 33 2d 31 36 2d 31 37 20
20 30 34 3a 33 32 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30
 37 32 20 54 65 73 74 4d 65 73 73 75 6e 67 30 30 32 35 2e 48 44 53 0d 0a 30 33 2
d 31 36 2d 31 37 20 20 30 34 3a 33 33 50 4d 20 20 20 20 20 20 20 20 20 20 20 20
20 20 20 31 32 32 37 34 34 20 54 65 73 74 4d 65 73 73 75 6e 67 30 30 32 35 2e 43
 53 56 0d 0a 30 33 2d 31 36 2d 31 37 20 20 30 34 3a 33 35 50 4d 20 20 20 20 20 2
0 20 20 20 20 20 20 20 20 20 20 31 35 30 30 30 20 54 65 73 74 4d 65 73 73 75 6e
67 30 30 32 36 2e 57 54 53 0d 0a 30 33 2d 31 36 2d 31 37 20 20 30 34 3a 33 35 50
 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 54 65 73 7
4 4d 65 73 73 75 6e 67 30 30 32 36 2e 48 44 53 0d 0a 30 33 2d 31 36 2d 31 37 20
20 30 34 3a 33 35 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 33 34 38
 33 35 20 54 65 73 74 4d 65 73 73 75 6e 67 30 30 32 36 2e 43 53 56 0d 0a 30 33 2
d 31 36 2d 31 37 20 20 30 34 3a 33 35 50 4d 20 20 20 20 20 20 20 20 20 20 20 20
20 20 20 20 31 35 30 30 30 20 54 65 73 74 4d 65 73 73 75 6e 67 30 30 32 37 2e 57
 54 53 0d 0a 30 33 2d 31 36 2d 31 37 20 20 30 34 3a 33 35 50 4d 20 20 20 ... >,
     <Buffer 6d 65 73 73 75 6e 67 30 31 5f 30 30 30 32 2e 43 53 56 0d 0a 30 33 2
d 32 38 2d 31 37 20 20 30 30 3a 34 36 50 4d 20 20 20 20 20 20 20 20 20 20 20 20
20 20 20 20 34 30 33 36 32 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 30
 31 5f 30 30 30 33 2e 43 53 56 0d 0a 30 33 2d 32 38 2d 31 37 20 20 30 33 3a 35 3
8 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 33 39 33 38 37 20 4c 65
69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 30 31 5f 30 30 30 34 2e 43 53 56 0d 0a
 30 33 2d 32 38 2d 31 37 20 20 30 34 3a 30 34 50 4d 20 20 20 20 20 20 20 20 20 2
0 20 20 20 20 20 20 33 36 33 39 39 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75
6e 67 30 31 5f 30 30 30 35 2e 43 53 56 0d 0a 30 33 2d 32 38 2d 31 37 20 20 30 34
 3a 30 35 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 34 30 33 39 38 2
0 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 30 31 5f 30 30 30 36 2e 43 53
56 0d 0a 30 33 2d 32 38 2d 31 37 20 20 30 34 3a 31 32 50 4d 20 20 20 20 20 20 20
 20 20 20 20 20 20 20 20 20 34 30 33 39 33 20 4c 65 69 73 74 75 6e 67 73 6d 65 7
3 73 75 6e 67 30 31 5f 30 30 30 37 2e 43 53 56 0d 0a 30 33 2d 32 38 2d 31 37 20
20 30 34 3a 31 33 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 34 30 34
 34 36 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 30 31 5f 30 30 30 38 2
e 43 53 56 0d 0a 30 33 2d 32 38 2d 31 37 20 20 30 34 3a 31 33 50 4d 20 20 20 20
20 20 20 20 20 20 20 20 20 20 20 20 34 30 34 30 30 20 4c 65 69 73 74 75 6e 67 73
 6d 65 73 73 75 6e 67 30 31 5f 30 30 30 39 2e 43 53 56 0d 0a 30 33 2d 32 ... >,
     <Buffer 30 34 2d 30 35 2d 31 37 20 20 30 38 3a 34 39 41 4d 20 20 20 20 20 2
0 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 4c 65 69 73 74 75 6e 67 73 6d
65 73 73 75 6e 67 49 6e 61 6e 30 30 30 36 2e 48 44 53 0d 0a 30 34 2d 30 35 2d 31
 37 20 20 30 38 3a 34 39 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 3
4 36 32 35 33 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30
30 30 36 2e 43 53 56 0d 0a 30 34 2d 30 35 2d 31 37 20 20 30 38 3a 35 33 41 4d 20
 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 39 37 32 30 20 4c 65 69 73 74 7
5 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 30 37 2e 57 54 53 0d 0a 30 34
2d 30 35 2d 31 37 20 20 30 38 3a 35 33 41 4d 20 20 20 20 20 20 20 20 20 20 20 20
 20 20 20 31 33 31 30 37 32 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 4
9 6e 61 6e 30 30 30 37 2e 48 44 53 0d 0a 30 34 2d 30 35 2d 31 37 20 20 30 38 3a
35 33 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 34 36 32 34 39 20 4c
 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 30 37 2e 43 53 5
6 0d 0a 30 34 2d 30 35 2d 31 37 20 20 30 38 3a 35 34 41 4d 20 20 20 20 20 20 20
20 20 20 20 20 20 20 20 20 32 33 38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d 65 73
 73 75 6e 67 49 6e 61 6e 30 30 30 38 2e 57 54 53 0d 0a 30 34 2d 30 35 2d 31 37 2
0 20 30 38 3a 35 34 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31
30 37 32 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 30
 38 2e 48 44 53 0d 0a 30 34 2d 30 35 2d 31 37 20 20 30 38 3a 35 34 41 4d ... >,
     <Buffer 20 20 20 20 20 20 20 20 20 20 20 32 33 38 30 30 20 4c 65 69 73 74 7
5 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 32 33 2e 57 54 53 0d 0a 30 34
2d 30 35 2d 31 37 20 20 30 36 3a 30 36 50 4d 20 20 20 20 20 20 20 20 20 20 20 20
 20 20 20 31 33 31 30 37 32 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 4
9 6e 61 6e 30 30 32 33 2e 48 44 53 0d 0a 30 34 2d 30 35 2d 31 37 20 20 30 36 3a
30 36 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 35 33 34 32 34 20 4c
 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 32 33 2e 43 53 5
6 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 38 3a 35 33 41 4d 20 20 20 20 20 20 20
20 20 20 20 20 20 20 20 20 32 33 38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d 65 73
 73 75 6e 67 49 6e 61 6e 30 30 32 34 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31 37 2
0 20 30 38 3a 35 33 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31
30 37 32 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 32
 34 2e 48 44 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 38 3a 35 33 41 4d 20 20 2
0 20 20 20 20 20 20 20 20 20 20 20 20 20 35 33 37 32 34 20 4c 65 69 73 74 75 6e
67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 32 34 2e 43 53 56 0d 0a 30 34 2d 30
 36 2d 31 37 20 20 30 38 3a 35 35 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 2
0 20 20 32 33 38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e
61 6e 30 30 32 35 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 38 3a 35 35
 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 ... >,
     <Buffer 30 34 2d 30 36 2d 31 37 20 20 30 39 3a 32 31 41 4d 20 20 20 20 20 2
0 20 20 20 20 20 20 20 20 20 20 35 33 36 39 34 20 4c 65 69 73 74 75 6e 67 73 6d
65 73 73 75 6e 67 49 6e 61 6e 30 30 33 39 2e 43 53 56 0d 0a>,
     <Buffer 30 34 2d 30 36 2d 31 37 20 20 30 39 3a 32 32 41 4d 20 20 20 20 20 2
0 20 20 20 20 20 20 20 20 20 20 32 33 38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d
65 73 73 75 6e 67 49 6e 61 6e 30 30 34 30 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31
 37 20 20 30 39 3a 32 32 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 3
3 31 30 37 32 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30
30 34 30 2e 48 44 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 39 3a 32 32 41 4d 20
 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 35 33 37 31 37 20 4c 65 69 73 74 7
5 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 34 30 2e 43 53 56 0d 0a 30 34
2d 30 36 2d 31 37 20 20 30 39 3a 32 33 41 4d 20 20 20 20 20 20 20 20 20 20 20 20
 20 20 20 20 32 33 38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 4
9 6e 61 6e 30 30 34 31 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 39 3a
32 33 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 4c
 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 34 31 2e 48 44 5
3 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 39 3a 32 33 41 4d 20 20 20 20 20 20 20
20 20 20 20 20 20 20 20 20 35 33 36 34 31 20 4c 65 69 73 74 75 6e 67 73 6d 65 73
 73 75 6e 67 49 6e 61 6e 30 30 34 31 2e 43 53 56 0d 0a 30 34 2d 30 36 2d 31 37 2
0 20 30 39 3a 32 38 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 32 33
37 33 32 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 34
 32 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 39 3a 32 38 41 4d ... >,
     <Buffer 20 20 20 20 20 20 20 20 20 20 20 35 33 36 30 37 20 4c 65 69 73 74 7
5 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 35 36 2e 43 53 56 0d 0a 30 34
2d 30 36 2d 31 37 20 20 30 39 3a 35 36 41 4d 20 20 20 20 20 20 20 20 20 20 20 20
 20 20 20 20 32 33 38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 4
9 6e 61 6e 30 30 35 37 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 39 3a
35 36 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 4c
 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 35 37 2e 48 44 5
3 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 39 3a 35 36 41 4d 20 20 20 20 20 20 20
20 20 20 20 20 20 20 20 20 35 33 36 33 37 20 4c 65 69 73 74 75 6e 67 73 6d 65 73
 73 75 6e 67 49 6e 61 6e 30 30 35 37 2e 43 53 56 0d 0a 30 34 2d 30 36 2d 31 37 2
0 20 31 30 3a 30 32 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 32 33
38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 35
 38 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 31 30 3a 30 32 41 4d 20 20 2
0 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 4c 65 69 73 74 75 6e
67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 35 38 2e 48 44 53 0d 0a 30 34 2d 30
 36 2d 31 37 20 20 31 30 3a 30 33 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 2
0 20 20 35 33 36 34 34 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e
61 6e 30 30 35 38 2e 43 53 56 0d 0a 30 34 2d 30 36 2d 31 37 20 20 31 30 3a 30 34
 41 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 32 33 38 30 30 20 ... >,
     <Buffer 30 34 2d 30 36 2d 31 37 20 20 30 34 3a 32 38 50 4d 20 20 20 20 20 2
0 20 20 20 20 20 20 20 20 20 20 32 33 38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d
65 73 73 75 6e 67 49 6e 61 6e 30 30 37 33 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31
 37 20 20 30 34 3a 32 38 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 3
3 31 30 37 32 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30
30 37 33 2e 48 44 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 34 3a 32 38 50 4d 20
 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 35 33 35 39 37 20 4c 65 69 73 74 7
5 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 37 33 2e 43 53 56 0d 0a 30 34
2d 30 36 2d 31 37 20 20 30 34 3a 32 39 50 4d 20 20 20 20 20 20 20 20 20 20 20 20
 20 20 20 20 32 33 38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 4
9 6e 61 6e 30 30 37 34 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 34 3a
32 39 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 33 31 30 37 32 20 4c
 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 37 34 2e 48 44 5
3 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 34 3a 32 39 50 4d 20 20 20 20 20 20 20
20 20 20 20 20 20 20 20 20 35 33 36 34 38 20 4c 65 69 73 74 75 6e 67 73 6d 65 73
 73 75 6e 67 49 6e 61 6e 30 30 37 34 2e 43 53 56 0d 0a 30 34 2d 30 36 2d 31 37 2
0 20 30 34 3a 33 35 50 4d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 32 33
38 30 30 20 4c 65 69 73 74 75 6e 67 73 6d 65 73 73 75 6e 67 49 6e 61 6e 30 30 37
 35 2e 57 54 53 0d 0a 30 34 2d 30 36 2d 31 37 20 20 30 34 3a 33 35 50 4d ... > ]
,
  pipeDataSize: 29157,
  holdQueue: true,
  callback: [Function],
  runLevel: 1,
  ended: 1491808598689,
  ping: 1513,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1491808597176 }
ExeQueue> Ending process, holding queue: LIST /USB-0`

**Comment by sparkida** [comment]
It looks like the output just isn't matching the regex at [line#1554](https://github.com/sparkida/ftpimp/blob/master/index.js#L1554), could you add a `console.log(data.toString())` right after [line#1692](https://github.com/sparkida/ftpimp/blob/master/index.js#L1692) and share the output (or some of it)

**Comment by iinnaann** [comment]
Output of data.toString()

`03-14-17  03:02PM                49152 Prufstand_010000.SET
03-14-17  03:12PM                 3424 Prufstand_0100000.CSV
04-10-17  00:39PM                23800 0704170000.WTS
04-10-17  00:39PM               131072 0704170000.HDS
04-10-17  00:39PM                53652 0704170000.CSV`

**Comment by sparkida** [comment]
Thanks for sharing, it's the same as I saw in buffer but wanted to make sure. I would like to fix this programmatically if possible, but not sure what server your FTP service is running on, if you know please share ;)

`ls` uses regex to match general *NIX output from `ls`, yours is different in this case, to fix we just need to make our own regex and override the default. I put this together for you to move things along....

***TLDR;*** paste after requiring `ftpimp`:

```javascript
var ftpimp = require('ftpimp');
//---
var StatObject = ftpimp.prototype.StatObject;
//matches your ls output
StatObject.prototype._reg = /([0-9\-]{8})\s+([0-9]{2}:[0-9]{2})([AP]M)\s+([0-9]+)\s+(.*)/;
//create a custom StatObject to process results from ls
let MyStatObject = function (stat) {
    let obj = this;
    obj.date = new Date(Date.parse([stat[1], stat[2], stat[3]].join(' ')));
    obj.size = stat[4];
    obj.filename = stat[5];
};
MyStatObject.prototype = StatObject.prototype;
//override default StatObject creation
StatObject.create = function (stat) {
    return new MyStatObject(stat);
};
// { date: 2017-03-14T22:02:00.000Z,
//   size: '49152',
//   filename: 'Prufstand_010000.SET' }

```

Hope that works for you, let me know if there is anything else.
- Nick

**Comment by iinnaann** [comment]
@sparkida thanks. Its working now. Don't know which os exactly but it's a unix os.
