### ISSUE TITLE
How can i catch ERRCONNRESET 

### ISSUE THREAD

**Issue by danilo94** [sparkida/ftpimp#35]
Hello, i'm using this library to download a group of files hosted in a ftp server. Sometimes it occours without problems. But sometimes i'm receive this Uncaught Error:

Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1050)
    at TCP.onread (net.js:581)

how can i catch this error ?

**Comment by sparkida** [comment]
It's difficult to say because I don't know the context wherein this occurs. Is this all you see? Can you provide any other info (maybe with debug=true)?

Best suggestion:
```
//first try attaching to the socket used by FTPimp
const FTP = require('ftpimp');
const ftp = FTP.create(config);
ftp.socket.on('error', (e) => {
   console.log('ftp', e);
});

//if that doesn't work, there is another connection created when you handle file data
ftp.pipe.on('error', (e) => {
  console.log('pipe', e);
});

//if all else fails
process.on('uncaughtException', (e) => {
  console.log('process', e);
});
```

Let me know if this gets you anything.

**Comment by sparkida** [comment]
Closing this for now, let me know if there is anything else
