### ISSUE TITLE
ls is broken

### ISSUE THREAD

**Issue by dacrhu** [sparkida/ftpimp#5]
Hi,

I try this:

ftp.connect(function () {
        ftp.ls('foldername/', function (err, data) {
                console.log(err, data);
         });
});

Result:

TypeError: Cannot read property '1' of null TypeError: Cannot read property '1' of null
    at Object.proto.StatObject.StatObject (/home/user/app/node_modules/ftpimp/ftpimp-app.js:1331:28)
    at Function.StatObject.create (/home/user/app/node_modules/ftpimp/ftpimp-app.js:1443:12)
    at /home/user/app/node_modules/ftpimp/ftpimp-app.js:1502:26
    at Function.<anonymous> (/home/user/app/node_modules/ftpimp/ftpimp-app.js:575:66)
    at exeProto._closePipe (/home/user/app/node_modules/ftpimp/ftpimp-app.js:304:23)
    at that.(anonymous function) [as closePipe] (/home/user/app/node_modules/ftpimp/ftpimp-app.js:244:32)
    at exeProto._receiveData (/home/user/app/node_modules/ftpimp/ftpimp-app.js:364:10)
    at Socket.that.(anonymous function) (/home/user/app/node_modules/ftpimp/ftpimp-app.js:244:32)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)

If I try with lsnames then ftpimp don't show all files of folder.
Thank you for your time!

**Comment by dacrhu** [comment]
Output of debug mode:

connect: callback
socket connected!
....................

>>>
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 6 of 25 allowed.
220-Local time is now 12:34. Server port: 21.
220-This is a private system - No anonymous login
220 You will be disconnected after 60 minutes of inactivity.
>>>

220
------------------
CODE  -> 220
 You will be disconnected after 60 minutes of inactivity.---------
------------------
>executing command: login
>Authenticating...
Cue> Registering callback...
false
0
Cue> Loading cue
Cue> Loaded...running
function () {
            dbg('Run> running callbackConstruct'.yellow + ' ' + command);
            if (command === 'QUIT') {
                ftp.cue.reset();
            }
            //var cueInstance = 
            ExeCue.create(command, callback, runNow, holdCue);
        }
Run> running callbackConstruct USER USERNAME
handle.data.waiting: true
 You will be disconnected after 60 minutes of inactivity. [privsep] [TLS] ----------
Run> command sent: USER USERNAME
....................

>>>
331 User USERNAME OK. Password required
>>>

331
------------------
CODE  -> 331
DATA -> User USERNAME OK. Password required
------------------
handle.data.waiting: true
handle.data.waiting:: 331 User USERNAME OK. Password required
calling : _responseHandler > USER USERNAME
{ '0': '331',
  '1': 'User USERNAME OK. Password required' }
Response handler: 331
User USERNAME OK. Password required
user sent
Cue> Registering callback...
true
0
calling : _checkProc > USER USERNAME
{}
ExeCue> Ending process: USER USERNAME
Event> endproc
Cue> Loading cue
Cue> Loaded...running
function () {
            dbg('Run> running callbackConstruct'.yellow + ' ' + command);
            if (command === 'QUIT') {
                ftp.cue.reset();
            }
            //var cueInstance = 
            ExeCue.create(command, callback, runNow, holdCue);
        }
Run> running callbackConstruct PASS PASSWORD
Run> command sent: PASS PASSWORD
....................

>>>
230-This server supports FXP transfers
230-OK. Current restricted directory is /
230 73922 Kbytes used (0%) - authorized: 10485760 Kb
>>>

230
------------------
CODE  -> 230
 73922 Kbytes used (0%) - authorized: 10485760 Kb
------------------
>executing command: ready
handle.data.waiting: true
 73922 Kbytes used (0%) - authorized: 10485760 KbXP transfers
calling : _responseHandler > PASS PASSWORD
{ '0': '230',
  '1': '-This server supports FXP transfers\r-OK. Current restricted directory is /\r 73922 Kbytes used (0%) - authorized: 10485760 Kb' }
Response handler: 230
password sent
 73922 Kbytes used (0%) - authorized: 10485760 Kb
SimpleCue> LIST > FOLDERNAME/*
LIST runCue ------ runNow?
undefined
SimpleCue::LIST> Running
SimpleCue::LIST> Opening data port
Cue> Registering callback...
true
0
calling : _checkProc > PASS PASSWORD
{}
ExeCue> Ending process: PASS PASSWORD
Event> endproc
Cue> Loading cue
Cue> Loaded...running
function () {
            dbg('Run> running callbackConstruct'.yellow + ' ' + command);
            if (command === 'QUIT') {
                ftp.cue.reset();
            }
            //var cueInstance = 
            ExeCue.create(command, callback, runNow, holdCue);
        }
Run> running callbackConstruct PASV 79,172,211,3
Run> command sent: PASV 79,172,211,3
....................

>>>
227 Entering Passive Mode (79,172,211,3,195,88)
>>>

227
------------------
CODE  -> 227
DATA -> Entering Passive Mode (79,172,211,3,195,88)
------------------
>executing command: startPassive
passive settings updated
handle.data.waiting: true
handle.data.waiting:: 227 Entering Passive Mode (79,172,211,3,195,88)
calling : _responseHandler > PASV 79,172,211,3
{ '0': '227',
  '1': 'Entering Passive Mode (79,172,211,3,195,88)' }
Response handler: 227
opening data port...
79.172.211.3
50008
passive connection established ... running callback
hook: function (data) {//{{{
    if (null === data) {
        return false;
    }
    dbg(data.grey);
    data = data.split('\r\n').filter(Boolean);
    var i = 0,
        cur,
        list = [];
        
    for(i; i < data.length; i++) {
        cur = StatObject.create(data[i]);
        list.push(cur);
        dbg(cur);
    }

    return list;
}
Run> running callbackConstruct LIST FOLDERNAME/*
Run> command sent: LIST FOLDERNAME/*
....................

>>>
150 Accepted data connection
>>>

150
------------------
CODE  -> 150
DATA -> Accepted data connection
------------------
>executing command: dataPortReady
---data port ready---
handle.data.waiting: true
handle.data.waiting:: 150 Accepted data connection
calling : _responseHandler > LIST FOLDERNAME/*
{ '0': '150', '1': 'Accepted data connection' }
Response handler: 150
listening for pipe data
calling : _receiveData > LIST FOLDERNAME/*
{ '0': <Buffer 2d 72 77 2d 72 2d 2d 72 2d 2d 20 20 20 20 31 20 38 30 20 20 20 20 20 20 20 20 20 77 77 77 20 20 20 20 20 20 20 20 20 20 20 31 36 39 38 31 34 35 20 44 65 ...> }
receiving......
calling : _closePipe > LIST FOLDERNAME/*
{}
closing.....
-rw-r--r--    1 80         www           1698145 Dec 11  2009 FOLDERNAME/01pdffile_01_14.pdf
-rw-r--r--    1 80         www           1758548 Dec 11  2009 FOLDERNAME/02pdffile_01_28.pdf
-rw-r--r--    1 80         www           1889222 Dec 11  2009 FOLDERNAME/03pdffile_02_04.pdf
-rw-r--r--    1 80         www           2062314 Dec 11  2009 FOLDERNAME/04pdffile_02_18.pdf
-rw-r--r--    1 80         www           1956010 Dec 11  2009 FOLDERNAME/05pdffile_03_04.pdf
-rw-r--r--    1 80         www           2120967 Dec 11  2009 FOLDERNAME/06pdffile_03_18.pdf
-rw-r--r--    1 80         www           2664466 Jul 29  2010 FOLDERNAME/07_27_pdffile_online.pdf
-rw-r--r--    1 80         www           2836443 Dec 11  2009 FOLDERNAME/07pdffile_04_01.pdf
-rw-r--r--    1 80         www           1904507 Dec 11  2009 FOLDERNAME/08pdffile_04_16.pdf
-rw-r--r--    1 80         www           2361306 Dec 11  2009 FOLDERNAME/09 pdffile_04_29.pdf
-rw-r--r--    1 80         www           2266801 Dec 11  2009 FOLDERNAME/10 pdffile_05_13.pdf
-rw-r--r--    1 80         www           1777229 Dec 11  2009 FOLDERNAME/11 pdffile_05_29.pdf
-rw-r--r--    1 80         www           1683351 Dec 11  2009 FOLDERNAME/12 pdffile_06_10.pdf
-rw-r--r--    1 80         www           2111241 Dec 11  2009 FOLDERNAME/13 pdffile_06_24.pdf
-rw-r--r--    1 80         www           1772970 Dec
ending transfer --- data received
callback 2 --
-rw-r--r--    1 80         www           1698145 Dec 11  2009 FOLDERNAME/01pdffile_01_14.pdf
-rw-r--r--    1 80         www           1758548 Dec 11  2009 FOLDERNAME/02pdffile_01_28.pdf
-rw-r--r--    1 80         www           1889222 Dec 11  2009 FOLDERNAME/03pdffile_02_04.pdf
-rw-r--r--    1 80         www           2062314 Dec 11  2009 FOLDERNAME/04pdffile_02_18.pdf
-rw-r--r--    1 80         www           1956010 Dec 11  2009 FOLDERNAME/05pdffile_03_04.pdf
-rw-r--r--    1 80         www           2120967 Dec 11  2009 FOLDERNAME/06pdffile_03_18.pdf
-rw-r--r--    1 80         www           2664466 Jul 29  2010 FOLDERNAME/07_27_pdffile_online.pdf
-rw-r--r--    1 80         www           2836443 Dec 11  2009 FOLDERNAME/07pdffile_04_01.pdf
-rw-r--r--    1 80         www           1904507 Dec 11  2009 FOLDERNAME/08pdffile_04_16.pdf
-rw-r--r--    1 80         www           2361306 Dec 11  2009 FOLDERNAME/09 pdffile_04_29.pdf
-rw-r--r--    1 80         www           2266801 Dec 11  2009 FOLDERNAME/10 pdffile_05_13.pdf
-rw-r--r--    1 80         www           1777229 Dec 11  2009 FOLDERNAME/11 pdffile_05_29.pdf
-rw-r--r--    1 80         www           1683351 Dec 11  2009 FOLDERNAME/12 pdffile_06_10.pdf
-rw-r--r--    1 80         www           2111241 Dec 11  2009 FOLDERNAME/13 pdffile_06_24.pdf
-rw-r--r--    1 80         www           1772970 Dec
======= 2015-03-17 12:34:29: TypeError: Cannot read property '1' of null TypeError: Cannot read property '1' of null
    at Object.proto.StatObject.StatObject (/home/user/app/node_modules/ftpimp/ftpimp-app.js:1331:28)
    at Function.StatObject.create (/home/user/app/node_modules/ftpimp/ftpimp-app.js:1443:12)
    at /home/user/app/node_modules/ftpimp/ftpimp-app.js:1502:26
    at Function.<anonymous> (/home/user/app/node_modules/ftpimp/ftpimp-app.js:575:66)
    at exeProto._closePipe (/home/user/app/node_modules/ftpimp/ftpimp-app.js:304:23)
    at that.(anonymous function) [as closePipe] (/home/user/app/node_modules/ftpimp/ftpimp-app.js:244:32)
    at exeProto._receiveData (/home/user/app/node_modules/ftpimp/ftpimp-app.js:364:10)
    at Socket.that.(anonymous function) (/home/user/app/node_modules/ftpimp/ftpimp-app.js:244:32)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
....................

>>>
226-Options: -a -l 
226 233 matches total
>>>

226
------------------
CODE  -> 226
 233 matches total-a -l 
------------------
>executing command: transferComplete
CMD> data transfer complete
running cue now
LIST runCue ------ runNow?
true
SimpleCue::LIST> Running
SimpleCue> Empty ... stopping
Event> endproc
Cue> Loading cue
--cue empty--
----> pipe end ----

**Comment by sparkida** [comment]
Thank you very much for your time in reporting this issue. The information you provided and the log were very helpful and I was able to quickly find and (I believe) fix the issue. Let me know if you come across anything else. - Nick

**Comment by dacrhu** [comment]
Thank you Nick! :)
