### ISSUE TITLE
ftp.save bug, unreadable file

### ISSUE THREAD

**Issue by jjunior187** [sparkida/ftpimp#7]
I'm simply trying to get a txt file from a remote server.
My code real simple :

```javascript
ftp.save(['web/nodeftp/index.txt', './local_copies/index.txt'], function (err, filename) {
	    	console.log('File transferred');
	});
```

And I'm getting this error :

```javascript
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Socket.emit (events.js:87:13)
    at CMD.error (C:\Sites\nodeftp\node_modules\ftpimp\lib\command.js:125:16)
    at run (C:\Sites\nodeftp\node_modules\ftpimp\index.js:820:29)
    at Socket.handle.data (C:\Sites\nodeftp\node_modules\ftpimp\index.js:852:9)
    at Socket.emit (events.js:129:20)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

However, when I'm trying to get files with other extensions than txt or html, such as pdf or mp3, the script work... Except that I can't open the transferred files.

**Comment by sparkida** [comment]
I'm assuming you're on the latest version 2.2.2?

Looking into this, I noticed an issue where the data starts with "null" #8, hopefully that resolves the other broken files.

The other thing I noticed is that your paths in the error log look like you're on Windows, but the paths for the files: ['web/nodeftp/index.txt', './local_copies/index.txt'] are both UNIX based (forward slash). Could you try changing those around to have proper slashes. The first one probably stays the same (if your ftp server is on linux) the second one I would use `path.join('local_copies', 'index.txt')`

maybe this will tell us something

**Comment by sparkida** [comment]
be sure to update to the latest version (2.2.3)
I'll try some more test tonight once I'm in front of a Windows machine
:)

**Comment by jjunior187** [comment]
thanks for the quick answer.
I've tried again some stuff this morning, the 'null' bug is now fixed trnaks to your last pull. But now when I save a local copy of a mp3 file, the file is created, but the size is twice the original one and it's still impossible to read.

I thought maybe it concerns the currentType. I've seen in the test that the currentType us switched according to the file extention, and that the default is ascii. Maybe the problem lies there, as I tried to save a png file and the problem was the same (file is created, but size is bigger than the original one, and it's impossible to read the file).

**Comment by sparkida** [comment]
Yea you're right on the money, currentType isn't being set properly, ftp.save will call ftp.get which uses ftp.setType before tranferring the file. The condition at https://github.com/sparkida/ftpimp/blob/master/index.js#L1953
should actually be `if (undefined !== ftp.ascii[ext]) {`, changing this should fix your problem until I get the next patch out which will also fix a race condition with ftp.save

**Comment by sparkida** [comment]
The new v2.2.31 should have fixed this issue, please let me know if the problem persists so I can reopen :)
